#!/bin/bash
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
repo=/home/celeron55/softat/minetest

workdir=$dir/work
rulesdir=$dir/rules.d

worldsdir=$workdir/worlds
clonedir=$workdir/repo
builddir=$workdir/builds

mkdir -p "$workdir"
mkdir -p "$worldsdir"
mkdir -p "$builddir"

echo "== Cloning repository from $repo to $clonedir"
rm -rf "$clonedir"
git clone "$repo" "$clonedir"

# Returns true if a built minetest already exists in $1
check_built_minetest ()
{
	mtdir=$1
	if [ -a "$mtdir/bin/minetestserver" ]; then
		return 0
	fi
	return 1
}

build_minetest ()
{
	tag=$1
	ruledir=$2
	pkg=$3
	mtdir=$4
	
	rm -rf "$mtdir"
	mkdir -p "$mtdir"
	pushd "$mtdir" &>/dev/null
		# Extract package
		tar -xf "$pkg"
		
		# Patch stuff
		for patchfile in $ruledir/*.patch; do
			if ! [ -a "$patchfile" ]; then
				continue
			fi
			echo "==     Patching $tag with $patchfile"
			patch -p1 < $patchfile
			if [ "$?" != "0" ]; then
				echo "!!     Patch failed"
				return 1
			fi
		done
		
		# Build it
		cmake . -DRUN_IN_PLACE=1 -DBUILD_CLIENT=0
		make -j2
		if [ "$?" == "1" ]; then
			echo "!!     Error building $tag"
			return 1
		else
			echo "--     Built $tag"
			rm -rf CMakeFiles src/CMakeFiles src/lua/CMakeFiles src/lua/build/CMakeFiles src/jthread/CMakeFiles
		fi
	popd &>/dev/null
	return 0
}

# Build all the versions, if not already built
for ruledir in $rulesdir/*; do
	tag=`cat "$ruledir/tag"`
	echo "== Checking build: $tag"
	mtdir=$builddir/minetest-$tag
	# Make package if doesn't already exist
	pkg="$builddir/$tag.tar"
	if [ -a "$pkg" ]; then
		echo "==   Package exists for $tag"
	else
		echo "==   Creating package for $tag"
		pushd $clonedir &>/dev/null
			git archive --format tar $tag > "$pkg"
		popd &>/dev/null
	fi
	# Build if hasn't already been built
	check_built_minetest "$mtdir"
	if [ "$?" == "0" ]; then
		echo "==   Already built: $tag"
	else
		echo "==   Building $tag"
		build_minetest "$tag" "$ruledir" "$pkg" "$mtdir"
		if ! [ "$?" == "0" ]; then
			echo "!!   Failed to build $tag"
		fi
	fi
done

# Make a world with each version
for ruledir in $rulesdir/*; do
	tag=`cat "$ruledir/tag"`
	echo "== Making world with version: $tag"
	mtdir=$builddir/minetest-$tag
	worlddir=$worldsdir/world-$tag
	#echo "== Running minetest-worldtest-makeworld.sh for $tag"
	
	# Check compatibility with itself
	rm -rf "$worlddir"
	$dir/minetest-worldtest-check-and-set.sh "$mtdir" "$worlddir"
	if [ "$?" == "0" ]; then
		echo "!! $tag returns valid for non-existent world"
	fi
	$dir/minetest-worldtest-check-and-set.sh "$mtdir" "$worlddir"
	if [ "$?" != "0" ]; then
		echo "!! $tag returns invalid for self-generated world"
	fi
	
	# TODO: Check worlds generated by previous versions
done


